### ISSUE TITLE
listener is not a function (ssr)

### ISSUE THREAD

**Issue by testica** [sheikalthaf/ngu-carousel#42]
I'm facing a problem with Server-side rendering
```
TypeError: this.listener1 is not a function
    at NguCarouselComponent.module.exports.NguCarouselComponent.ngOnDestroy (/var/task/dist/server.js:175618:14)
    at callProviderLifecycles (/var/task/dist/server.js:13032:18)
    at callElementProvidersLifecycles (/var/task/dist/server.js:12997:13)
    at callLifecycleHooksChildrenFirst (/var/task/dist/server.js:12981:17)
    at destroyView (/var/task/dist/server.js:14325:5)
    at callViewAction (/var/task/dist/server.js:14476:13)
    at execEmbeddedViewsAction (/var/task/dist/server.js:14414:17)
    at destroyView (/var/task/dist/server.js:14323:5)
    at callViewAction (/var/task/dist/server.js:14476:13)
    at execComponentViewsAction (/var/task/dist/server.js:14388:13)
```

**Comment by sheikalthaf** [comment]
Hi @testica ,
Thanks for reporting. I will try to solve it

**Comment by kenho1703** [comment]
Hello
Please update, Change from 
 this.listener1();
 this.listener2();
To 
if (this.listener1) {
       this.listener1();     
 }
 if (this.listener2) {
       this.listener2()
}

**Comment by arun-maddheshia** [comment]
@sheikalthaf i am also facing this issue :( with SSR

**Comment by sheikalthaf** [comment]
@testica @arun-maddheshia @kenho1703 This issue is fixed. Please check release.

Thanks
